### ISSUE TITLE
导入时出现问题from sign import preprocess ImportError: cannot import name 'preprocess' from 'sign'

### ISSUE THREAD

**Issue by maopi-boom** [boating-in-autumn-rain/Bearing-fault-Diagnosis-based-on-deep-learning#1]
from sign import preprocess
ImportError: cannot import name 'preprocess' from 'sign'

**Comment by boating-in-autumn-rain** [comment]
您好，2023年2月5日前，我会将此仓库的代码重新更新一次，争取不出现歧义的部分，出现这个问题，提供两个思路：1.不要用汉化软件，导包会出现问题。2.将所有代码clone下来，应该是能够运行的，如果还是不能运行，那么就将preprocess的其他目录py文件复制到你现在的项目文件夹下，就可以了
